name: isep_platform
description: ISEP Platform Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # WebSocket
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^12.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # Maps
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Image
  image_picker: ^1.0.7
  cached_network_image: ^3.3.0
  stomp_dart_client: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

